version: '3'

services: 
  php-fpm:
    build:
      context: ./php-fpm
#    command: chmod -R 777 /var/www/var/cache;  
    env_file:      
      - ./variables.env
    volumes:
      - ../app:/var/www
    networks:
      - app-network
    ports:
      - "9000:9000"

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm    
    ports:
      - "80:80"
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
    #command: --explicit_defaults_for_timestamp
    volumes:
      - ../app:/var/www
      - ./mysql/data:/var/lib/mysql      
      - ./logs:/var/log 
    env_file:
      - ./variables.env
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
